### ISSUE TITLE
Error When Using the Library in WSL

### ISSUE THREAD

**Issue by AlexKlo** [bhftbootcamp/LightweightCharts.jl#24]
Describe the bug
---
> An issue arises when using the LightweightCharts.jl library in WSL. Specifically, the `lwc_show` method fails because the sequence of conditions in the [open_browser](https://github.com/bhftbootcamp/LightweightCharts.jl/blob/467362a374cdcb21b2b0ef443ffc4ff3836f0e20/src/LightweightCharts.jl#L365) method is incorrect.

Problem Details:

- The method `Sys.islinux()` returns `true` for WSL, but the command needed to open a browser with an `.html` file in WSL differs from a standard Linux environment.

- A potential quick fix is to reorder the conditions in the open_browser method.

- Additionally, noticed that the [detectwsl()](https://github.com/bhftbootcamp/LightweightCharts.jl/blob/467362a374cdcb21b2b0ef443ffc4ff3836f0e20/src/LightweightCharts.jl#L372) method is not defined in the LightweightCharts.jl package.

To Reproduce
---
> Launch Julia on WSL.
> Copy the first [example ](https://github.com/bhftbootcamp/LightweightCharts.jl/tree/467362a374cdcb21b2b0ef443ffc4ff3836f0e20?tab=readme-ov-file#usage)from the `README.md `of the LightweightCharts.jl library.
> Paste the code into the REPL and execute it.

```julia
julia> using LightweightCharts

julia> t_values = round(Int64, time()) .+ collect(1:500);

julia> x_values = sin.((1:500) / 10);

julia> chart = lwc_line(
           t_values,
           x_values;
           label_name = "lwc_line",
           line_color = "orange",
           line_width = 4,
           line_style = LWC_SOLID,
           line_type = LWC_STEP,
           price_scale_id = LWC_LEFT,
           plugins = LWCPlugin[
               lwc_trend_line(100, 0.32, 200, 0.86; line_color = "#9d4edd"),
               # lwc_delta_tooltip(),
               # lwc_vert_line(150),
               # lwc_crosshair_highlight_bar(),
               # lwc_tooltip(; title = "my_tooltip")
           ],
       )
LightweightCharts.LWCChart(lwc_line)


julia> lwc_show(chart)
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "/home/alex/lightweightcharts.html"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

true
```

Expected behavior
---
> A browser window should open displaying the chart.

Additional context
---
> `julia> versioninfo()`
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 1 on 20 virtual cores
Environment:
  JULIA_IMAGE_THREADS = 1
> `pkg> st`
Project LightweightCharts v2.2.0
Status `~/bhft/bhft_libs/LightweightCharts.jl/Project.toml`
  [46f1a544] NanoDates v1.0.3
  [db9b398d] Serde v3.4.1
  [ade2ca70] Dates

**Comment by gryumov** [comment]
https://github.com/bhftbootcamp/LightweightCharts.jl/pull/25
